export interface User {
  id: number,
  first_name: string,
  last_name: string,
  email: string,
  gender: 'Male' | 'Female' | 'Agender' | 'Genderqueer',
  city: string,
  address: string
}
export const users: User[] =
[{"id":1,"first_name":"Dennie","last_name":"O'Hearn","email":"dohearn0@prnewswire.com","gender":"Male","city":"Huilongshan","address":"3 Union Way"},
{"id":2,"first_name":"Alexandrina","last_name":"Menham","email":"amenham1@ft.com","gender":"Female","city":"Ampera","address":"1320 Hintze Court"},
{"id":3,"first_name":"Ag","last_name":"Tabour","email":"atabour2@sphinn.com","gender":"Female","city":"Lagayan","address":"90 Corry Point"},
{"id":4,"first_name":"Chris","last_name":"Kurten","email":"ckurten3@dailymotion.com","gender":"Male","city":"Kaynardzha","address":"16753 Kim Pass"},
{"id":5,"first_name":"Sherwin","last_name":"Valett","email":"svalett4@vk.com","gender":"Male","city":"Sandyford","address":"3 La Follette Plaza"},
{"id":6,"first_name":"Wain","last_name":"Ironside","email":"wironside5@arizona.edu","gender":"Male","city":"That Phanom","address":"9899 Mitchell Parkway"},
{"id":7,"first_name":"Valina","last_name":"Minci","email":"vminci6@zimbio.com","gender":"Agender","city":"Shitouhe","address":"7067 Bunting Avenue"},
{"id":8,"first_name":"Harley","last_name":"Peach","email":"hpeach7@slideshare.net","gender":"Male","city":"Sant Julià de Lòria","address":"6823 5th Parkway"},
{"id":9,"first_name":"Conrad","last_name":"Shanks","email":"cshanks8@earthlink.net","gender":"Male","city":"Ciechocin","address":"111 Esker Hill"},
{"id":10,"first_name":"Bryn","last_name":"Swainsbury","email":"bswainsbury9@mapquest.com","gender":"Male","city":"Kirs","address":"38993 Rowland Point"},
{"id":11,"first_name":"Derry","last_name":"MacGiffin","email":"dmacgiffina@livejournal.com","gender":"Male","city":"Tromsø","address":"5 Brickson Park Hill"},
{"id":12,"first_name":"Dave","last_name":"Brookwell","email":"dbrookwellb@i2i.jp","gender":"Male","city":"Hitachi","address":"4279 Dwight Parkway"},
{"id":13,"first_name":"Casie","last_name":"Ripley","email":"cripleyc@hao123.com","gender":"Female","city":"Citeureup","address":"7 Golden Leaf Parkway"},
{"id":14,"first_name":"Xylia","last_name":"Crawley","email":"xcrawleyd@about.com","gender":"Genderqueer","city":"eMbalenhle","address":"50980 Fordem Center"},
{"id":15,"first_name":"Margot","last_name":"Searl","email":"msearle@feedburner.com","gender":"Female","city":"Rząśnik","address":"350 Stephen Lane"},
{"id":16,"first_name":"Brnaba","last_name":"Bickerstaffe","email":"bbickerstaffef@furl.net","gender":"Male","city":"Hiseti","address":"77305 Manitowish Junction"},
{"id":17,"first_name":"Frans","last_name":"Kennicott","email":"fkennicottg@technorati.com","gender":"Male","city":"Quintela","address":"29 Corscot Parkway"},
{"id":18,"first_name":"Noelle","last_name":"Cappleman","email":"ncapplemanh@hostgator.com","gender":"Female","city":"Vishnyakovskiye Dachi","address":"19297 Sullivan Junction"},
{"id":19,"first_name":"Tamera","last_name":"Lamanby","email":"tlamanbyi@pagesperso-orange.fr","gender":"Female","city":"Baruny","address":"8746 Service Avenue"},
{"id":20,"first_name":"Fay","last_name":"Spilsburie","email":"fspilsburiej@goodreads.com","gender":"Female","city":"Kuala Terengganu","address":"5379 Bashford Pass"},
{"id":21,"first_name":"Petronia","last_name":"Jacobssen","email":"pjacobssenk@businessinsider.com","gender":"Female","city":"Landskrona","address":"3963 Bowman Parkway"},
{"id":22,"first_name":"Cordelie","last_name":"Boone","email":"cboonel@vimeo.com","gender":"Female","city":"Głuchołazy","address":"487 Becker Center"},
{"id":23,"first_name":"Archibold","last_name":"Cornelissen","email":"acornelissenm@cafepress.com","gender":"Male","city":"Ciawitali","address":"4 Manley Hill"},
{"id":24,"first_name":"Rebe","last_name":"Crosoer","email":"rcrosoern@elpais.com","gender":"Female","city":"Kafir Qala","address":"88576 Arrowood Hill"},
{"id":25,"first_name":"Jarret","last_name":"Tant","email":"jtanto@ycombinator.com","gender":"Male","city":"Gandusari","address":"8 Mayer Center"},
{"id":26,"first_name":"Alyosha","last_name":"Carnegie","email":"acarnegiep@google.com.au","gender":"Male","city":"San Antonio","address":"163 Mendota Parkway"},
{"id":27,"first_name":"Kariotta","last_name":"Castagne","email":"kcastagneq@facebook.com","gender":"Female","city":"Buyun","address":"43 Aberg Hill"},
{"id":28,"first_name":"Chase","last_name":"Reveley","email":"creveleyr@geocities.jp","gender":"Male","city":"Jugantang","address":"443 Sullivan Lane"},
{"id":29,"first_name":"Dawn","last_name":"Darlaston","email":"ddarlastons@google.es","gender":"Female","city":"Fengshan","address":"4 Starling Center"},
{"id":30,"first_name":"Chauncey","last_name":"Lewisham","email":"clewishamt@clickbank.net","gender":"Male","city":"Živinice","address":"8525 Heath Parkway"},
{"id":31,"first_name":"Emlyn","last_name":"Liccardi","email":"eliccardiu@ft.com","gender":"Female","city":"Carora","address":"75625 Little Fleur Circle"},
{"id":32,"first_name":"Normie","last_name":"Coveley","email":"ncoveleyv@pinterest.com","gender":"Male","city":"Lidian","address":"27812 Mitchell Court"},
{"id":33,"first_name":"Chrystel","last_name":"McAuliffe","email":"cmcauliffew@histats.com","gender":"Agender","city":"Grenoble","address":"1 Memorial Lane"},
{"id":34,"first_name":"Garry","last_name":"Brignell","email":"gbrignellx@xrea.com","gender":"Male","city":"Drayton Valley","address":"9 Schiller Park"},
{"id":35,"first_name":"Harmonia","last_name":"Insko","email":"hinskoy@jigsy.com","gender":"Female","city":"Langnga","address":"48761 Springview Pass"},
{"id":36,"first_name":"Sonnie","last_name":"Pina","email":"spinaz@who.int","gender":"Male","city":"Haparanda","address":"70 Summit Hill"},
{"id":37,"first_name":"Patsy","last_name":"Jeandot","email":"pjeandot10@bizjournals.com","gender":"Female","city":"Rumoi","address":"941 Montana Plaza"},
{"id":38,"first_name":"Paulette","last_name":"Lukovic","email":"plukovic11@booking.com","gender":"Female","city":"Urukh","address":"533 Bonner Hill"},
{"id":39,"first_name":"Corey","last_name":"Shales","email":"cshales12@nytimes.com","gender":"Female","city":"Sayansk","address":"70 Elgar Point"},
{"id":40,"first_name":"Aveline","last_name":"Rummin","email":"arummin13@irs.gov","gender":"Female","city":"Seltjarnarnes","address":"8 Lakeland Trail"},
{"id":41,"first_name":"Abbot","last_name":"Strang","email":"astrang14@live.com","gender":"Male","city":"Göteborg","address":"8 Florence Parkway"},
{"id":42,"first_name":"Lynelle","last_name":"Denty","email":"ldenty15@cbslocal.com","gender":"Female","city":"Tuqiao","address":"6 Carberry Circle"},
{"id":43,"first_name":"Hedwiga","last_name":"Boykett","email":"hboykett16@lycos.com","gender":"Female","city":"Bordeaux","address":"00208 Montana Center"},
{"id":44,"first_name":"Sharl","last_name":"Abbot","email":"sabbot17@liveinternet.ru","gender":"Female","city":"Kayan","address":"890 Hermina Parkway"},
{"id":45,"first_name":"Maddie","last_name":"Bunner","email":"mbunner18@vistaprint.com","gender":"Female","city":"Miami","address":"375 Armistice Circle"},
{"id":46,"first_name":"Jakie","last_name":"Cunrado","email":"jcunrado19@paginegialle.it","gender":"Male","city":"Gayam","address":"1002 Claremont Street"},
{"id":47,"first_name":"Maurice","last_name":"Mutimer","email":"mmutimer1a@youtu.be","gender":"Male","city":"Dolores","address":"89 Autumn Leaf Lane"},
{"id":48,"first_name":"Jobye","last_name":"Britten","email":"jbritten1b@mail.ru","gender":"Female","city":"Castanheira","address":"96350 Reindahl Road"},
{"id":49,"first_name":"Cathleen","last_name":"Allix","email":"callix1c@is.gd","gender":"Female","city":"Orzesze","address":"7 Eastlawn Way"},
{"id":50,"first_name":"Mordecai","last_name":"Wong","email":"mwong1d@cisco.com","gender":"Male","city":"Gorelki","address":"6753 Randy Court"}]
